feat: improve Eludris rest errors (`ErrorResponse`)
eludris/eludris pull request #60
Opened 2023-04-27 00:25 UTC by EnokiUN

## Description

This PR aims to improve how errors in Eludris work to make it easier to work with both server and client wise.

To do so, this PR removes the old (very stupid) way of handling errors and utilises a single enum with some shared data and a macro as to make the code much cleaner.

(also I noticed some quite regarded code whilst refactoring Effis so that also got fixed)

This is related to #34 but does not close it just yet.

## This is a **Code Change**

- [ ] Docs have been updated to reflect these changes if necessary.
- [x] Changes have been tested.

2023-04-27 21:15 UTC, ooliver1 commented on todel/src/http/response.rs
> +            ErrorResponse::RateLimited { shared, .. } => shared.status,
Excuse me?

2023-04-27 21:18 UTC, ooliver1 requested changes

2023-04-27 21:18 UTC, ooliver1 commented on todel/src/models/response.rs
> +/// Magic marco that handles instantiating [`ErrorResponse`] variants.
```suggestion
/// Magic marco that handles instantiating [`ErrorResponse`] variants.
```

2023-04-27 21:18 UTC, ooliver1 commented on todel/src/models/response.rs
> +/// It also handles wrapping and returning them when a ratelimiter is passed as the first argument.
```suggestion
/// It also handles wrapping and returning them when a rate limiter is passed as the first argument.
```

2023-04-27 21:20 UTC, EnokiUN commented on todel/src/http/response.rs
> +            ErrorResponse::RateLimited { shared, .. } => shared.status,
I know not of a better way to do it

2023-04-27 21:20 UTC, ooliver1 commented on todel/src/http/response.rs
> +            ErrorResponse::RateLimited { shared, .. } => shared.status,
ok :neckbeard:

2023-04-29 16:52 UTC, ooliver1 approved these changes

2023-04-29 16:56 UTC, merged