feat(pandemonium): share one connection for writing and reading ratelimit info
eludris/eludris pull request #65
Opened 2023-05-05 14:17 UTC by EnokiUN

## Description

2 connections / user -> 1 connection / user

This may fix the pandemonium bug

## This is a **Code Change**

- [x] Docs have been updated to reflect these changes if necessary.
- [x] Changes have been tested.

2023-05-05 14:30 UTC, toolifelesstocode requested changes

2023-05-05 14:30 UTC, toolifelesstocode commented on pandemonium/src/main.rs
> +            .context("Could't get an async connection to redis")?,
```suggestion
            .context("Couldn't get an async connection to redis")?,
```

2023-05-10 07:48 UTC, ooliver1 approved these changes
No docs to misspell, someone turned their brain on.

2023-05-10 08:13 UTC, thesadru approved these changes
no

2023-05-10 11:26 UTC, merged